dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-7


script:
  - mkdir build
  - cd build
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-6 cmake ../src
  - cmake --build .
  - ./tests
